# Generated by Django 2.1.7 on 2020-04-06 14:37

from django.db import migrations, models
import djongo.models.fields
import myProj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('participants_list', djongo.models.fields.ArrayModelField(model_container=myProj.models.Student)),
            ],
        ),
    ]
