# Generated by Django 2.1.7 on 2020-04-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=2)),
                ('division', models.CharField(max_length=1)),
                ('subject', models.CharField(max_length=20)),
                ('faculty', models.CharField(max_length=4)),
            ],
        ),
    ]
