# Generated by Django 2.1.7 on 2020-04-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.CharField(default='', max_length=3),
        ),
    ]
