# Generated by Django 2.1.7 on 2020-04-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='', max_length=2)),
                ('division', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(default='', max_length=25)),
                ('faculty_init', models.CharField(default='', max_length=4)),
                ('faculty_branch', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_dob',
        ),
        migrations.AddField(
            model_name='student',
            name='student_branch',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='student_div',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together={('branch', 'division')},
        ),
    ]
