# Generated by Django 2.1.7 on 2020-04-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProj', '0002_auto_20200406_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
    ]
